version = 0.1
[dev.deploy.parameters]
stack_name = "sam-app-dev"
resolve_s3 = true
s3_prefix = "sam-app-dev"
region = "us-east-1"
confirm_changeset = true
profile = "sam"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
