AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"
Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: back_end/index_aws.handler
      Runtime: nodejs22.x
      Timeout: 60
      MemorySize: 128
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref Weights
      Events:
        CheckUsername:
          Type: Api
          Properties:
            Path: /check-username
            Method: post
        CheckWeight:
          Type: Api
          Properties:
            Path: /check-weight
            Method: post
        GetWeeklyLeaderboard: 
          Type: Api
          Properties:
            Path: /get-weekly-leaderboard
            Method: get
        GetOverallLeaderboard:
          Type: Api
          Properties:
            Path: /get-overall-leaderboard
            Method: get
        GetUserStat:
          Type: Api
          Properties:
            Path: /get-user-stat
            Method: get
        CheckIndexForm:
          Type: Api
          Properties:
            Path: /check-index-form
            Method: post

  StepsApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: back_end/index_aws_steps.handler
      Runtime: nodejs22.x
      Timeout: 60
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Steps
      Events:
        LoginSteps:
          Type: Api
          Properties:
            Path: /login_steps
            Method: post
        SubmitSteps:
          Type: Api
          Properties:
            Path: /submit_steps
            Method: post
        GetOverallStepsLeaderboard:
          Type: Api
          Properties:
            Path: /overall_steps_leaderboard
            Method: get
        GetWeeklyStepsLeaderboard:
          Type: Api
          Properties:
            Path: /weekly_steps_leaderboard
            Method: get
        GetUserStepsStats:
          Type: Api
          Properties:
            Path: /user_steps_stats/{username}
            Method: get

  Weights:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Weights
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  Steps:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Steps
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WeightsTableName:
    Description: "Weights DynamoDB Table Name"
    Value: !Ref Weights
  StepsTableName:
    Description: "Steps DynamoDB Table Name"
    Value: !Ref Steps
