baseURL = "/"
languageCode = "en-us"
title = "Biggest Loser 2025"

[params]
  description = "APH Biggest Loser 2025 Challenge"
  author = "APH Wellness Committee"

[menu]
  [[menu.main]]
    identifier = "leaderboard"
    name = "Leaderboard"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "form"
    name = "Weight Entry"
    url = "/form/"
    weight = 2 