AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Biggest Loser Project

Resources:
  BiggestLoserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: back_end/lambda.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: .
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          MONGO_URI: "mongodb://127.0.0.1:27017/weightTracker"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY